name: ClaimBiomes
main: com.bradengoodwin.claimbiomes.ClaimBiomes
version: 1.0.0
author: b_e_a_n_

############################################################
# +------------------------------------------------------+ #
# |                   ClaimBiomes commands               | #
# +------------------------------------------------------+ #
############################################################
commands:
  claimbiome:
    description: This is a demo command.
    usage: /claimbiom <name>
    permission: claimbiomes.claimbiome
    permission-message: You don't have permission to claim biomes

